config/routes.rb
Rails.application.routes.draw do
  

  

  resources :comments
  resources :favorites

   get "posts/search" => "posts#search"

  get 'pages/home'
  
  devise_for :users
  resources :users do
    resources :pictures
    resources :posts do
      resources :favorites
      resources :comments
    end
  end
  
  get "search" => "posts#search"
  
  get "favorites/list_favorites" => "favorites#list_favorites"
  get "list_favorites" => "favorites#list_favorites"

  root to: "pages#home"
  get "home" => "pages#home"

  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
validates :user_id, presence: true
validates :post_id, presence: true
validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]
  # GET /comments
  # GET /comments.json
  def index
     @post=Post.find(params[:post_id])
     @comments = Comment.where(post_id: params[:post_id])
     @comment = Comment.new
     @comment.user=current_user
     @comment.post=@post
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    
  end

 
  # GET /comments/new
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    @comment.user=current_user
    @comment.post=@post
  end

  # GET /comments/1/edit
  def edit
    
    @post=Post.find(params[:post_id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to user_post_comments_path(params[:user_id], params[:post_id]), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to user_post_comments_path(params[:user_id],params[:post_id] ), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|          
      format.html { redirect_to user_post_comments_path(@comment.post.user.id, @comment.post.id), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([current_user, @post, @comment]) do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :post_id %>
    <%= f.hidden_field :id %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
   <%= tinymce %>
    <%= f.text_area :content, :class => "tinymce" %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Destroy', user_post_comment_path(user_id: @comment.post.user.id,  post_id: @comment.post.id, id: @comment.id ), method: :delete,
           data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Back', :back %>

app/views/comments/index.html.erb
<h3>Comments to:  <%=  @post.title %> </h3>
<table>
  

  
    <% @comments.each do |comment| %>
      

        <%= link_to comment.user.nickname, user_posts_path(comment.user.id) %><br />
        <%= comment.content.html_safe %><br />
        <%= comment.created_at %><br />
        <%= link_to 'Show', user_post_comment_path(comment.post.user.id, comment.post.id, comment.id) %>
        <% if user_signed_in? %>
          <% if comment.user == current_user %>
         
         | <%= link_to 'Edit', edit_user_post_comment_path(current_user.id, comment.post.id, comment.id) %>
         | <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
         <% end %>
        <%end%>
        <br />
        <br />
    <% end %>

<% if user_signed_in? %>
 <p> Write new comment: </p>
 <%= render 'form' %>
<% end %>
<%= link_to 'Back to post', user_post_path(@post.user.id,@post.id) %>

<br>

app/views/comments/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to @comment.user.nickname, user_posts_path(@comment.user.id) %>
 
</p>

<p>
  <strong><%= @comment.post.title %></strong>
  
</p>

<p>
  
  <%= @comment.content.html_safe %><br />
  <%= @comment.created_at %><br />
</p>
<% if user_signed_in? %>
  <% if @comment.user == current_user %>
  <%= link_to 'Edit', edit_user_post_comment_path(user_id: @comment.post.user.id, post_id: @comment.post.id, id: @comment.id) %> |
  <%= link_to 'Destroy', user_post_comment_path(user_id: @comment.post.user.id,  post_id: @comment.post.id, id: @comment.id ), method: :delete,
           data: { confirm: 'Are you sure?' } %>|
  <% end %>
<%end%>
<%= link_to 'All comments', user_post_comments_path(@comment.post.user.id, @comment.post.id) %>