config/routes.rb
Rails.application.routes.draw do
  

  

  resources :comments
  resources :favorites

   get "posts/search" => "posts#search"

  get 'pages/home'
  
  devise_for :users
  resources :users do
    resources :pictures
    resources :posts do
      resources :favorites
      resources :comments
    end
  end
  
  get "search" => "posts#search"
  
  get "favorites/list_favorites" => "favorites#list_favorites"
  get "list_favorites" => "favorites#list_favorites"

  root to: "pages#home"
  get "home" => "pages#home"

  
  

end

app/views/pages/home.html.erb
<title>Startseite </title>


<body>

		<div class="row">
        <div class="col-sm-8 blog-main">          
            
             <% @posts.each do |post| %>
             <% next if post.privacy == true && current_user != post.user %>
             <br />
             <br />             

              <% @c=Comment.where(post_id: post.id).count %>
              
                <div class="blog-post">
                <h2 class="blog-post-title"><%= post.title %></h2>
                <p class="blog-post-meta"><%= post.created_at %>, by <%= link_to post.user.nickname, user_posts_path(post.user.id)%></p>


             <p>
             <%= post.content.html_safe %>
              <% if post.tag != "" %>
              <br />
                 # 
                 <% @tags=post.tag.split(",") %>
                 <% @tags.each do |tag| %>
                   <%= link_to "#{tag}", search_path(search: tag) %> &nbsp;
                 <%end%>
              <%end%>
                                     
               <br />
             <%= link_to 'Show post', user_post_path(user_id: post.user.id, id: post.id) %>
             |<%= link_to "#{@c} Comments",  user_post_comments_path(post.user.id, post.id) %>
             <% if user_signed_in? %>
             <% f=Favorite.where("user_id = ? AND post_id = ?", current_user.id, post.id) %>
              <% if f.empty? %>
               |<%= link_to 'Favorite',  new_user_post_favorite_path(current_user,post.id) %>
               | <% end %>
              <%end%>
             </p>

             </div>
             <% end %> 
     </div>
     </div>
     </div>
     <br />
     <br />
    
    
    </body>

   <div class="blog-footer">
      <a href="javascript:scroll(0,0);">Back to top</a>   
    </div>