config/routes.rb
Rails.application.routes.draw do
  

  

  resources :comments
  resources :favorites

   get "posts/search" => "posts#search"

  get 'pages/home'
  
  devise_for :users
  resources :users do
    resources :pictures
    resources :posts do
      resources :favorites
      resources :comments
    end
  end
  
  get "search" => "posts#search"
  
  get "favorites/list_favorites" => "favorites#list_favorites"
  get "list_favorites" => "favorites#list_favorites"

  root to: "pages#home"
  get "home" => "pages#home"

  
  

end

app/models/post.rb
class Post < ActiveRecord::Base
mount_uploader :picture, PictureUploader
validates :title, presence: true
validates :content, presence: true


belongs_to :user
has_many :comments, dependent: :destroy

 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
skip_before_action :authenticate_user!, only: [:show, :index, :search]
  # GET /posts
  # GET /posts.json
  def index
  @posts = Post.where(user_id: params[:user_id]).order(created_at: :desc)
  @user=User.find(params[:user_id])
  @u=@user.nickname

       end


  def search 
    @posts= Post.where("tag like ?","%#{params[:search]}%")+Post.where("title like ?","%#{params[:search]}%")

  end


  
  # GET /posts/1
  # GET /posts/1.json
  # 
  def show
   @c=Comment.where(post_id: @post.id).count
  @user=User.where(user_id: params[:user_id])
  
   end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id=current_user.id
    @picture=PictureUploader.new
    if params[:picture] != nil
     picture.store!(File.open(params[:post][:picture].path))
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_path(user_id: @post.user.id,  id: @post.id), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to user_post_path(user_id: @post.user.id,  id: @post.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
     @posts = Post.where(user_id: params[:user_id])
    respond_to do |format|
      format.html { redirect_to user_posts_path(@post.user.id), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :tag, :privacy, :picture)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for([current_user, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :size=>"60" %>
  </div>
  <div class="field">
  <%= tinymce  %>
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => "tinymce", :escape => false %>
  </div>



  <div class="field">
    <%= f.label "Tags (delimit by comma)" %><br>
    <%= f.text_field :tag %>
  </div>
  <br />
  <div class="field">
  
  <%= f.label "picture upload" %>
  <%= f.file_field :picture %>
  <%= f.label "remove picture"%>
  <%= f.check_box :remove_picture! %>
  
     


    </label>
  
  <br />
    <%= f.radio_button(:privacy, true) %>
      <%= f.label(:privacy, "private (visible only to me)") %>
      <br />
    <%= f.radio_button(:privacy, false, checked: true ) %>
      <%= f.label(:privacy, "public ") %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<title>Eintrag bearbeiten</title> 

<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', [current_user, @post] %> |
<%= link_to 'Back to post', user_post_path(@post.user.id,@post.id) %>

app/views/posts/index.html.erb
<title> Blogg </title>


<h1><%= @u %>'s Blogg</h1>
  <%= link_to "show profile", user_path(@user) %>
   |
    <% if user_signed_in? %>
     <% if current_user == @user %>
     <%= link_to 'New Post', new_user_post_path %>
     <% end%>
     <% end %>
     <br />

    <% @posts.each do |post| %>
     <% next if post.privacy == true && current_user != post.user %>

    
      <% @c=Comment.where(post_id: post.id).count %>
     <br />
     <div class="blog-post">
                <h2 class="blog-post-title"><%= post.title %></h2>
                <p class="blog-post-meta"><%= post.created_at %>, by <%= link_to post.user.nickname, user_posts_path(post.user.id)%></p>
     
      
        <%= post.content.html_safe %>
        
        <% if post.tag != "" %>
           <br />
             # 
           <% @tags=post.tag.split(",") %>
           <% @tags.each do |tag| %>
           <%= link_to "#{tag}", search_path(search: tag) %> &nbsp;
             <%end%>
        <% end %>
         
        <br />
        <%= link_to 'Show post', user_post_path(user_id: post.user.id,  id: post.id) %> 
       |<%= link_to "#{@c} Comments",  user_post_comments_path(post.user.id, post.id) %>
       <% if user_signed_in? %>

                <% f=Favorite.where("user_id = ? AND post_id = ?", current_user, post.id) %>
              <% if f.empty? %>
               |<%= link_to 'Favorite',  new_user_post_favorite_path(current_user,post.id) %>
              <%end%>
         <% if post.user.id == current_user.id %>
         |<%= link_to 'Edit', edit_user_post_path(post.user.id, post.id) %>
         |<%= link_to 'Delete post', user_post_path(user_id: post.user.id,  id: post.id), method: :delete,
           data: { confirm: 'Are you sure?' } %>
           <%end%>
       <%end%>
       </div>
      <% end %>



<div class="blog-footer">
      <a href="javascript:scroll(0,0);">Back to top</a>   
    </div>

app/views/posts/new.html.erb
<title> Neuer Eintrag </title>

<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/posts/search.html.erb
<% if @posts.empty? %>
No matching posts found
<%end %>

<% @posts.each do |post| %>
             <% next if post.privacy == true && current_user != post.user %>

             <br />
             <br />
              <% @c=Comment.where(post_id: post.id).count %>
             <%= link_to post.user.nickname, user_posts_path(post.user.id)%><br />

               <div class="blog-post">
               <h2 class="blog-post-title"><%= post.title %></h2>
              <p class="blog-post-meta"><%= post.created_at %>, by <%= link_to post.user.nickname, user_posts_path(post.user.id)%></p>
     

             <%= post.content.html_safe %>
               
            <% if post.tag != "" %>
           <br />
             # 
           <% @tags=post.tag.split(",") %>
           <% @tags.each do |tag| %>
           <%= link_to "#{tag}", search_path(search: tag) %> &nbsp;
             <%end%>
        <% end %>
          <br />

             <%= link_to 'Show post', user_post_path(user_id: post.user.id, id: post.id) %>
             |<%= link_to "#{@c} Comments",  user_post_comments_path(post.user.id, post.id) %>
             <% if user_signed_in? %>
             <% f=Favorite.where("user_id = ? AND post_id = ?", current_user, post.id) %>
             <% if f.empty? %>
               |<%= link_to 'Favorite',  new_user_post_favorite_path(current_user,post.id) %>
              <% end %>
             <% end %>
             </div>
             <% end %>

app/views/posts/show.html.erb
<!DOCTYPE html>
 <%if @post.privacy == true && current_user!= @post.user %>
 Private post, can't open it!

<%else%>
<title> <%= @post.title %> </title>

<p id="notice"><%= notice %></p>


   <div class="blog-post">
     <h2 class="blog-post-title"><%= @post.title %></h2>
     <p class="blog-post-meta"><%= @post.created_at %>, by <%= link_to @post.user.nickname, user_posts_path(@post.user.id)%></p>
     



  <%= @post.content.html_safe %>
  
  
  <% if @post.picture_url != nil%>
  <br />
    <%= image_tag @post.picture_url %>
  <%end%>

   <% if @post.tag != "" %>
           <br />
             # 
           <% @tags=@post.tag.split(",") %>
           <% @tags.each do |tag| %>
           <%= link_to "#{tag}", search_path(search: tag) %> &nbsp;
             <%end%>
        <% end %>
       
<br />
<% if user_signed_in? %>
  <% if current_user == @post.user %>
  <%= link_to 'Edit', edit_user_post_path(user_id: @post.user.id,  id: @post.id) %> |
  <%= link_to 'Delete post', user_post_path(user_id: @post.user.id,  id: @post.id), method: :delete,
           data: { confirm: 'Are you sure?' } %>
  <%end%>
<% end %>
|<%= link_to "#{@c} Comments",  user_post_comments_path(@post.user.id, @post.id) %>
<%if user_signed_in? %>
<% f=Favorite.where("user_id = ? AND post_id = ?", current_user, @post.id) %>
 <% if f.empty? %>
 |<%= link_to 'Favorite',  new_user_post_favorite_path(current_user,@post.id) %>
 <% end %>
<% end %>
</div>
<%end%>

</html>