config/routes.rb
Rails.application.routes.draw do
  

  

  resources :comments
  resources :favorites

   get "posts/search" => "posts#search"

  get 'pages/home'
  
  devise_for :users
  resources :users do
    resources :pictures
    resources :posts do
      resources :favorites
      resources :comments
    end
  end
  
  get "search" => "posts#search"
  
  get "favorites/list_favorites" => "favorites#list_favorites"
  get "list_favorites" => "favorites#list_favorites"

  root to: "pages#home"
  get "home" => "pages#home"

  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<head>
  <title><%= @title  || Blogg %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="blog-header">
        <h1 class="blog-title">BloG:Gates to another World</h1>       
      </div>    

 <nav class="blog-nav">
   
       <ul class="hmenu">
       <li><%=link_to "BLOGG", home_path %></li>
        <% if user_signed_in? %>
         <li><%= link_to current_user.nickname, user_posts_path(current_user.id) %></li>
         <li><%= link_to "Favorites", list_favorites_path %></li>
         <li><%= link_to "Edit profile", edit_user_path(current_user.id) %></li>
        <% end %>
        <li><%= render 'devise/menu/registration_items' %></li>
       <li><%= render 'devise/menu/login_items' %></li>
       <li> <%=link_to "All users", users_path %></li>
        <li ><%= form_tag search_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
          <% end %></li>

       </ul>
       
      </nav>


<%= yield %>



</html>